-- MySQL Script generated by MySQL Workbench
-- Wed May 24 14:31:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema phpinit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema phpinit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `phpinit` DEFAULT CHARACTER SET utf8 ;
USE `phpinit` ;

-- -----------------------------------------------------
-- Table `phpinit`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpinit`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phpinit`.`profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpinit`.`profession` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phpinit`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phpinit`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profile_id` INT NOT NULL,
  `profession_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_profile_idx` (`profile_id` ASC),
  INDEX `fk_user_profession1_idx` (`profession_id` ASC),
  CONSTRAINT `fk_user_profile`
    FOREIGN KEY (`profile_id`)
    REFERENCES `phpinit`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_profession1`
    FOREIGN KEY (`profession_id`)
    REFERENCES `phpinit`.`profession` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
